@url = http://localhost:5127/users-module
@email = user@confab.io
@password = secret
@role = user
@accessToken = secret ### GET {{url}}
@accessToken2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWEwY2JhOS05MDUzLTRlNTctYmM0ZS03Nzc1YzI1OWJmNzgiLCJ1bmlxdWVfbmFtZSI6IjM1YTBjYmE5LTkwNTMtNGU1Ny1iYzRlLTc3NzVjMjU5YmY3OCIsImp0aSI6IjFlMWY1ZmY4LTBkODEtNDBiNi1iNmIwLWU5NWY2NGRmMGQ4ZSIsImlhdCI6IjE2MzkwNjgzMTEwNTkiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInRpY2tldHMiLCJ1c2VycyJdLCJuYmYiOjE2MzkwNjgzMTEsImV4cCI6MTYzOTEwNDMxMSwiaXNzIjoiY29uZmFiIn0._YsO89ndZxgirG8o7pEgMSqEd-p1v4OfE5jKTrJ6t40
###
GET {{url}}

### 
GET {{url}}/account
Authorization: Bearer {{accessToken2}}

###
POST {{url}}/account/sign-up
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}",
    "role": "{{role}}",
    "claims": 
    {
        "permissions": ["conferences", "hosts", "tickets", "users"]
    }
}

### 
POST {{url}}/account/sign-in 
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}