@url = http://localhost:5127/conferences-module
@hostId = 691e9adc-6c70-4107-bfa1-0f4787cbda60
@conferenceId = 3b64e24c-50d4-40a4-b9d1-93b2e1ed26e9
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWEwY2JhOS05MDUzLTRlNTctYmM0ZS03Nzc1YzI1OWJmNzgiLCJ1bmlxdWVfbmFtZSI6IjM1YTBjYmE5LTkwNTMtNGU1Ny1iYzRlLTc3NzVjMjU5YmY3OCIsImp0aSI6Ijk2Mjk4ZjE4LTJlZTQtNDc3OC05ZTZhLTJlZGVkYTU1NTM4ZCIsImlhdCI6IjE2NDI0MzE2MzE2NDQiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInRpY2tldHMiLCJ1c2VycyJdLCJuYmYiOjE2NDI0MzE2MzEsImV4cCI6MTY0MjQ2NzYzMSwiaXNzIjoiY29uZmFiIn0.KCAzGC32WWWFin4Q0sOEPdJKbV0XVCHuRD44cjYJTMk
###
GET {{url}}

###
POST {{url}}/hosts
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name":"Host #1",
    "description":"Lorem ipsum"
}

###
GET {{url}}/hosts

###
GET {{url}}/hosts/{{hostId}}

###
PUT {{url}}/hosts/{{hostId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name":"Host #2"
}

###
DELETE {{url}}/hosts/{{hostId}}
Content-Type: application/json




###
POST {{url}}/conferences
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "hostId":"{{hostId}}",
    "name":"Conference #1",
    "description":"Lorem ipsum",
    "location":"Test 123",
    "from":"2021-05-01",
    "to":"2021-05-02",
    "participantsLimit":100,
    "logoUrl":null
}

###
GET {{url}}/conferences

###
GET {{url}}/conferences/{{conferenceId}}

###
PUT {{url}}/conferences/{{conferenceId}}
Content-Type: application/json

{
    "name":"Conference #2",
    "description":"Lorem ipsum",
    "location":"Test 123",
    "from":"2021-05-01",
    "to":"2021-05-02",
    "participantsLimit":100,
    "logoUrl":null
}

###
DELETE {{url}}/conferences/{{conferenceId}}
Content-Type: application/json