@url = http://localhost:5127/speakers-module
@speakerId = 7ba6bd19-22d0-431f-80bc-30c55ca197d8
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNWEwY2JhOS05MDUzLTRlNTctYmM0ZS03Nzc1YzI1OWJmNzgiLCJ1bmlxdWVfbmFtZSI6IjM1YTBjYmE5LTkwNTMtNGU1Ny1iYzRlLTc3NzVjMjU5YmY3OCIsImp0aSI6ImRjYTMyNzZmLWY2YzAtNDhmYS04M2U5LTkxMGM0MDFmYTg3ZiIsImlhdCI6IjE2NDIxNzkyNDIyOTYiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInRpY2tldHMiLCJ1c2VycyJdLCJuYmYiOjE2NDIxNzkyNDIsImV4cCI6MTY0MjIxNTI0MiwiaXNzIjoiY29uZmFiIn0.kiFAnyye5AiTxoQMS9wSlKHBBbYC2UvzqN-ZqkkUHTw

###
GET {{url}}

###
POST {{url}}/speakers
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "firstName":"Test",
    "lastName":"Testowy",
    "email":"TestTestowy@email.com",
    "Bio":"Test string"
}

###
GET {{url}}/speakers

###
GET {{url}}/speakers/{{speakerId}}

###
PUT {{url}}/speakers/{{speakerId}}
Content-Type: application/json

{
    "firstName":"Jan",
    "lastName":"Testowy",
    "email":"TestTestowy@email.com",
    "Bio":"Test string"
}

###
DELETE {{url}}/speakers/{{speakerId}}
Content-Type: application/json